// Code generated by sudo-gen merge. DO NOT EDIT.

package nested

type ConfigPartial struct {
	Name *string      `json:"name,omitempty"`
	Jobs []Job        `json:"jobs,omitempty"`
	Home *HomePartial `json:"home,omitempty"`
}

type JobPartial struct {
	Title    *string `json:"title,omitempty"`
	Company  *string `json:"company,omitempty"`
	Location *string `json:"location,omitempty"`
}

type HomePartial struct {
	Address *string `json:"address,omitempty"`
	City    *string `json:"city,omitempty"`
	ZipCode *string `json:"zip_code,omitempty"`
}
