// Code generated by sudo-gen merge. DO NOT EDIT.

package nested

func (c *Config) ApplyPartial(p *ConfigPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Name != nil {
		c.Name = *p.Name
	}
	if p.Jobs != nil {
		c.Jobs = make([]Job, len(p.Jobs))
		copy(c.Jobs, p.Jobs)
	}
	if p.Home != nil {
		c.Home.ApplyPartial(p.Home)
	}
}

func (c *Job) ApplyPartial(p *JobPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Title != nil {
		c.Title = *p.Title
	}
	if p.Company != nil {
		c.Company = *p.Company
	}
	if p.Location != nil {
		c.Location = *p.Location
	}
}

func (c *Home) ApplyPartial(p *HomePartial) {
	if c == nil || p == nil {
		return
	}
	if p.Address != nil {
		c.Address = *p.Address
	}
	if p.City != nil {
		c.City = *p.City
	}
	if p.ZipCode != nil {
		c.ZipCode = *p.ZipCode
	}
}
