// Code generated by sudo-gen copy. DO NOT EDIT.

package nested

import (
	"testing"
)

func TestConfigCopyNil(t *testing.T) {
	var c *Config
	got := c.Copy()
	if got != nil {
		t.Errorf("expected nil, got %v", got)
	}
}

func TestConfigCopyEmpty(t *testing.T) {
	c := &Config{}
	got := c.Copy()
	if got == nil {
		t.Fatal("expected non-nil copy")
	}
	if got == c {
		t.Error("copy should be a different pointer")
	}
}

func TestConfigCopyIndependence(t *testing.T) {
	c := &Config{}
	got := c.Copy()

	// Modify original - copy should not change
	// This is a basic test; manual verification recommended for complex types
	if got == c {
		t.Error("copy should be independent from original")
	}
}

func TestConfigCopy_JobsSlice(t *testing.T) {
	c := &Config{
		Jobs: make([]Job, 2),
	}
	got := c.Copy()
	if got.Jobs == nil {
		t.Fatal("expected slice to be copied")
	}
	if len(got.Jobs) != len(c.Jobs) {
		t.Errorf("expected len %d, got %d", len(c.Jobs), len(got.Jobs))
	}
	// Verify independence by checking slice headers differ
	if len(c.Jobs) > 0 && &got.Jobs[0] == &c.Jobs[0] {
		t.Error("slice should be a deep copy, not share backing array")
	}
}

func TestConfigCopy_JobsSliceNil(t *testing.T) {
	c := &Config{}
	got := c.Copy()
	if got.Jobs != nil {
		t.Error("nil slice should remain nil after copy")
	}
}

func TestConfigCopy_JobsSliceIndependence(t *testing.T) {
	c := &Config{
		Jobs: make([]Job, 1),
	}
	got := c.Copy()
	if len(c.Jobs) == 0 {
		t.Skip("slice has no elements to test")
	}
	// Original slice length should not affect copy length
	originalLen := len(c.Jobs)
	c.Jobs = append(c.Jobs, c.Jobs[0])
	if len(got.Jobs) != originalLen {
		t.Error("modifications to original slice should not affect copy")
	}
}

func TestJobCopyNil(t *testing.T) {
	var c *Job
	got := c.Copy()
	if got != nil {
		t.Errorf("expected nil, got %v", got)
	}
}

func TestJobCopyEmpty(t *testing.T) {
	c := &Job{}
	got := c.Copy()
	if got == nil {
		t.Fatal("expected non-nil copy")
	}
	if got == c {
		t.Error("copy should be a different pointer")
	}
}

func TestHomeCopyNil(t *testing.T) {
	var c *Home
	got := c.Copy()
	if got != nil {
		t.Errorf("expected nil, got %v", got)
	}
}

func TestHomeCopyEmpty(t *testing.T) {
	c := &Home{}
	got := c.Copy()
	if got == nil {
		t.Fatal("expected non-nil copy")
	}
	if got == c {
		t.Error("copy should be a different pointer")
	}
}
