// Code generated by sudo-gen equals. DO NOT EDIT.

package nested

// Equal returns true if c and other have the same values.
func (c *Config) Equal(other *Config) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Name != other.Name {
		return false
	}
	if len(c.Jobs) != len(other.Jobs) {
		return false
	}
	for i := range c.Jobs {
		if !c.Jobs[i].Equal(&other.Jobs[i]) {
			return false
		}
	}
	if !c.Home.Equal(&other.Home) {
		return false
	}
	return true
}

// Equal returns true if c and other have the same values.
func (c *Job) Equal(other *Job) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Title != other.Title {
		return false
	}
	if c.Company != other.Company {
		return false
	}
	if c.Location != other.Location {
		return false
	}
	return true
}

// Equal returns true if c and other have the same values.
func (c *Home) Equal(other *Home) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Address != other.Address {
		return false
	}
	if c.City != other.City {
		return false
	}
	if c.ZipCode != other.ZipCode {
		return false
	}
	return true
}
