// Code generated by sudo-gen equals. DO NOT EDIT.

package nested

import (
	"testing"
)

func TestConfigEqualBothNil(t *testing.T) {
	var a, b *Config
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestConfigEqualOneNil(t *testing.T) {
	a := &Config{}
	var b *Config
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestConfigEqualSamePointer(t *testing.T) {
	a := &Config{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestConfigEqualEmptyStructs(t *testing.T) {
	a := &Config{}
	b := &Config{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}

func TestJobEqualBothNil(t *testing.T) {
	var a, b *Job
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestJobEqualOneNil(t *testing.T) {
	a := &Job{}
	var b *Job
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestJobEqualSamePointer(t *testing.T) {
	a := &Job{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestJobEqualEmptyStructs(t *testing.T) {
	a := &Job{}
	b := &Job{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}

func TestCoordinatesEqualBothNil(t *testing.T) {
	var a, b *Coordinates
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestCoordinatesEqualOneNil(t *testing.T) {
	a := &Coordinates{}
	var b *Coordinates
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestCoordinatesEqualSamePointer(t *testing.T) {
	a := &Coordinates{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestCoordinatesEqualEmptyStructs(t *testing.T) {
	a := &Coordinates{}
	b := &Coordinates{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}

func TestHomeEqualBothNil(t *testing.T) {
	var a, b *Home
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestHomeEqualOneNil(t *testing.T) {
	a := &Home{}
	var b *Home
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestHomeEqualSamePointer(t *testing.T) {
	a := &Home{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestHomeEqualEmptyStructs(t *testing.T) {
	a := &Home{}
	b := &Home{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}
