// Code generated by sudo-gen copy. DO NOT EDIT.

package nested

// Copy creates a deep copy of the Config.
func (c *Config) Copy() *Config {
	if c == nil {
		return nil
	}
	dst := &Config{}
	dst.Name = c.Name
	if c.Jobs != nil {
		dst.Jobs = make([]Job, len(c.Jobs))
		for i := range c.Jobs {
			dst.Jobs[i] = *c.Jobs[i].Copy()
		}
	}
	dst.Home = *c.Home.Copy()
	if c.OtherHome != nil {
		dst.OtherHome = c.OtherHome.Copy()
	}
	dst.CreatedAt = c.CreatedAt
	return dst
}

func (c *Job) Copy() *Job {
	if c == nil {
		return nil
	}
	dst := &Job{}
	dst.Title = c.Title
	dst.Company = c.Company
	dst.Location = c.Location
	return dst
}

func (c *Home) Copy() *Home {
	if c == nil {
		return nil
	}
	dst := &Home{}
	dst.Address = c.Address
	dst.City = c.City
	dst.ZipCode = c.ZipCode
	return dst
}
