// Code generated by sudo-gen merge. DO NOT EDIT.

package nested

import (
	"github.com/bobcob7/sudo-gen/examples/nested/duration"
)

func (c *Config) ApplyPartial(p *ConfigPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Name != nil {
		c.Name = *p.Name
	}
	if p.Jobs != nil {
		c.Jobs = make([]Job, len(p.Jobs))
		copy(c.Jobs, p.Jobs)
	}
	if p.Home != nil {
		c.Home.ApplyPartial(p.Home)
	}
	if p.OtherHome != nil {
		if c.OtherHome == nil {
			c.OtherHome = &Home{}
		}
		c.OtherHome.ApplyPartial(p.OtherHome)
	}
	if p.CreatedAt != nil {
		c.CreatedAt = *p.CreatedAt
	}
	if p.Limit != nil {
		applyDurationTimestampPartial(&c.Limit, p.Limit)
	}
}

func (c *Job) ApplyPartial(p *JobPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Title != nil {
		c.Title = *p.Title
	}
	if p.Company != nil {
		c.Company = *p.Company
	}
	if p.Location != nil {
		c.Location = *p.Location
	}
	if p.Tenure != nil {
		if c.Tenure == nil {
			c.Tenure = &duration.Timestamp{}
		}
		applyDurationTimestampPartial(c.Tenure, p.Tenure)
	}
	if p.Coords != nil {
		if c.Coords == nil {
			c.Coords = &Coordinates{}
		}
		c.Coords.ApplyPartial(p.Coords)
	}
}

// applyDurationTimestampPartial applies a partial update to a duration.Timestamp.
func applyDurationTimestampPartial(c *duration.Timestamp, p *DurationTimestampPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Minutes != nil {
		c.Minutes = *p.Minutes
	}
	if p.Hours != nil {
		c.Hours = *p.Hours
	}
	if p.Days != nil {
		c.Days = *p.Days
	}
}

func (c *Coordinates) ApplyPartial(p *CoordinatesPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Latitude != nil {
		c.Latitude = *p.Latitude
	}
	if p.Longitude != nil {
		c.Longitude = *p.Longitude
	}
}

func (c *Home) ApplyPartial(p *HomePartial) {
	if c == nil || p == nil {
		return
	}
	if p.Address != nil {
		c.Address = *p.Address
	}
	if p.City != nil {
		c.City = *p.City
	}
	if p.ZipCode != nil {
		c.ZipCode = *p.ZipCode
	}
	if p.Age != nil {
		c.Age = *p.Age
	}
	if p.Coords != nil {
		c.Coords.ApplyPartial(p.Coords)
	}
	if p.Destination != nil {
		if c.Destination == nil {
			c.Destination = &Coordinates{}
		}
		c.Destination.ApplyPartial(p.Destination)
	}
}
