// Code generated by sudo-gen merge. DO NOT EDIT.

package nested

import (
	"github.com/bobcob7/sudo-gen/examples/nested/duration"
	"time"
)

type ConfigPartial struct {
	Name      *string      `json:"name,omitempty"`
	Jobs      []Job        `json:"jobs,omitempty"`
	Home      *HomePartial `json:"home,omitempty"`
	OtherHome *HomePartial `json:"home,omitempty"`
	CreatedAt *time.Time   `json:"created_at,omitempty"`
}

type JobPartial struct {
	Title    *string                   `json:"title,omitempty"`
	Company  *string                   `json:"company,omitempty"`
	Location *string                   `json:"location,omitempty"`
	Tenure   *DurationTimestampPartial `json:"tenure,omitempty"`
}

type DurationTimestampPartial struct {
	Minutes *int `json:"minutes,omitempty"`
	Hours   *int `json:"hours,omitempty"`
	Days    *int `json:"days,omitempty"`
}

type HomePartial struct {
	Address *string `json:"address,omitempty"`
	City    *string `json:"city,omitempty"`
	ZipCode *string `json:"zip_code,omitempty"`
	Age     *duration.Duration
}
