// Code generated by sudo-gen layerbroker. DO NOT EDIT.

package nested

import (
	"encoding/json"
	"testing"
	"time"
)

func configPtr[T any](v T) *T {
	return &v
}

func TestConfigLayerBrokerUnsubscribe(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Name: "test"})
	var updates []string
	unsub := broker.SubscribeName(func(v string) {
		updates = append(updates, v)
	})
	if len(updates) != 1 {
		t.Fatalf("expected 1 update, got %d", len(updates))
	}
	broker.Layer().Set(&ConfigPartial{Name: configPtr("changed")})
	if len(updates) != 2 {
		t.Fatalf("expected 2 updates, got %d", len(updates))
	}
	unsub()
	broker.Layer().Set(&ConfigPartial{Name: configPtr("ignored")})
	if len(updates) != 2 {
		t.Fatalf("expected 2 updates after unsubscribe, got %d", len(updates))
	}
	if broker.Get().Name != "ignored" {
		t.Errorf("expected Name=ignored, got %s", broker.Get().Name)
	}
}

func TestConfigLayerBrokerSubscribeToEmptyField(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	var callCount int
	unsub := broker.SubscribeName(func(v string) {
		callCount++
	})
	defer unsub()

	// Should not be called initially since field is empty
	if callCount != 0 {
		t.Errorf("expected 0 calls for empty field, got %d", callCount)
	}

	// Should be called when field is set
	broker.Layer().Set(&ConfigPartial{Name: configPtr("test")})
	if callCount != 1 {
		t.Errorf("expected 1 call after setting field, got %d", callCount)
	}
}

func TestConfigLayerBrokerNilPartial(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{})
	broker.Layer().Set(nil) // should not panic
}

func TestConfigLayerBrokerGetReturnsIndependentCopy(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{})
	cfg1 := broker.Get()
	cfg2 := broker.Get()

	if cfg1 == cfg2 {
		t.Error("Get() should return independent copies, not the same pointer")
	}
}

func TestConfigLayerBrokerConcurrentLayerCreation(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	done := make(chan bool)

	// Create layers concurrently
	for i := 0; i < 10; i++ {
		go func() {
			layer := broker.Layer()
			if layer == nil {
				t.Error("Layer() returned nil")
			}
			done <- true
		}()
	}

	for i := 0; i < 10; i++ {
		<-done
	}
}

func TestConfigLayerBrokerBaseConfigPreserved(t *testing.T) {

	broker := NewConfigLayerBroker(&Config{Name: "base"})
	layer := broker.Layer()
	layer.Set(&ConfigPartial{Name: configPtr("layer")})

	cfg := broker.Get()
	if cfg.Name != "layer" {
		t.Errorf("expected Name=layer, got %s", cfg.Name)
	}

	// Create new broker to verify base is not mutated
	broker2 := NewConfigLayerBroker(&Config{Name: "base"})
	cfg2 := broker2.Get()
	if cfg2.Name != "base" {
		t.Errorf("base config should be preserved, got %s", cfg2.Name)
	}

}

func TestConfigLayerBrokerSubscribeJobsSlice(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Jobs: []Job{}})
	var callCount int
	unsub := broker.SubscribeJobs(func(v []Job) {
		callCount++
	})
	defer unsub()
	// Empty slice is non-nil, so should get initial callback
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
	// Set a new slice
	broker.Layer().Set(&ConfigPartial{Jobs: make([]Job, 3)})
	if callCount != 2 {
		t.Fatalf("expected 2 callbacks after update, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeOtherHomeStruct(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{OtherHome: &Home{}})
	var callCount int
	unsub := broker.SubscribeOtherHome(func(v *Home) {
		callCount++
	})
	defer unsub()
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeCreatedAtTime(t *testing.T) {
	now := time.Now()
	broker := NewConfigLayerBroker(&Config{CreatedAt: now})
	var updates []time.Time
	unsub := broker.SubscribeCreatedAt(func(v time.Time) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || !updates[0].Equal(now) {
		t.Fatalf("expected initial callback with current time, got %v", updates)
	}
	later := now.Add(time.Hour)
	broker.Layer().Set(&ConfigPartial{CreatedAt: &later})
	if len(updates) != 2 || !updates[1].Equal(later) {
		t.Fatalf("expected update callback with later time, got %v", updates)
	}
}

func TestConfigLayerBrokerMarshalJSON(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	layer.Set(&ConfigPartial{Name: configPtr("test")})
	data, err := json.Marshal(broker)
	if err != nil {
		t.Fatalf("MarshalJSON failed: %v", err)
	}
	if len(data) == 0 {
		t.Error("expected non-empty JSON output")
	}
	// Verify it's valid JSON
	var result map[string]any
	if err := json.Unmarshal(data, &result); err != nil {
		t.Fatalf("result is not valid JSON: %v", err)
	}
	if _, ok := result["base"]; !ok {
		t.Error("expected 'base' field in JSON output")
	}
	if _, ok := result["layers"]; !ok {
		t.Error("expected 'layers' field in JSON output")
	}
	if _, ok := result["final"]; !ok {
		t.Error("expected 'final' field in JSON output")
	}
}

func TestConfigLayerBrokerMarshalJSONEmpty(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	data, err := json.Marshal(broker)
	if err != nil {
		t.Fatalf("MarshalJSON failed: %v", err)
	}
	if len(data) == 0 {
		t.Error("expected non-empty JSON output")
	}
}

func TestConfigLayerBrokerSetAllFieldTypes(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	// Test setting all field types to exercise mergePartial
	partial := &ConfigPartial{}
	partial.Name = configPtr("test")

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetSliceAndMapFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{}
	partial.Jobs = make([]Job, 1)

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetPointerFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{}

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetNestedStructOtherHome(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{
		OtherHome: &HomePartial{},
	}
	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting nested struct")
	}
}

func TestConfigLayerBrokerSetTimeFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	now := time.Now()
	partial := &ConfigPartial{}
	partial.CreatedAt = &now

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting time fields")
	}
}
