package equals

const equalsTemplate = `// Code generated by sudo-gen equals. DO NOT EDIT.

package {{.Package}}

{{range .Structs}}
// {{$.MethodName}} returns true if c and other have the same values.
func (c *{{.Name}}) {{$.MethodName}}(other *{{.Name}}) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
{{- range .Fields}}
{{- if .IsPointer}}
{{- if isLocalStruct .}}
	if !c.{{.Name}}.{{$.MethodName}}(other.{{.Name}}) {
		return false
	}
{{- else if eq .TypePkg "time"}}
	if (c.{{.Name}} == nil) != (other.{{.Name}} == nil) {
		return false
	}
	if c.{{.Name}} != nil && !c.{{.Name}}.Equal(*other.{{.Name}}) {
		return false
	}
{{- else}}
	if (c.{{.Name}} == nil) != (other.{{.Name}} == nil) {
		return false
	}
	if c.{{.Name}} != nil && *c.{{.Name}} != *other.{{.Name}} {
		return false
	}
{{- end}}
{{- else if .IsSlice}}
	if len(c.{{.Name}}) != len(other.{{.Name}}) {
		return false
	}
	for i := range c.{{.Name}} {
{{- if and .StructTypeName (eq .TypePkg "")}}
		if !c.{{.Name}}[i].{{$.MethodName}}(&other.{{.Name}}[i]) {
			return false
		}
{{- else}}
		if c.{{.Name}}[i] != other.{{.Name}}[i] {
			return false
		}
{{- end}}
	}
{{- else if .IsMap}}
	if len(c.{{.Name}}) != len(other.{{.Name}}) {
		return false
	}
	for k, v := range c.{{.Name}} {
		ov, ok := other.{{.Name}}[k]
		if !ok {
			return false
		}
{{- if eq .TypeName "map[string]any"}}
		if !equalAny(v, ov) {
			return false
		}
{{- else}}
		if v != ov {
			return false
		}
{{- end}}
	}
{{- else if isLocalStruct .}}
	if !c.{{.Name}}.{{$.MethodName}}(other.{{.Name}}) {
		return false
	}
{{- else if eq .TypePkg "time"}}
	if !c.{{.Name}}.Equal(other.{{.Name}}) {
		return false
	}
{{- else}}
	if c.{{.Name}} != other.{{.Name}} {
		return false
	}
{{- end}}
{{- end}}
	return true
}
{{end}}
{{- $needsEqualAny := false}}
{{- range .Structs}}
{{- range .Fields}}
{{- if eq .TypeName "map[string]any"}}
{{- $needsEqualAny = true}}
{{- end}}
{{- end}}
{{- end}}
{{- if $needsEqualAny}}

func equalAny(a, b any) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	switch av := a.(type) {
	case map[string]any:
		bv, ok := b.(map[string]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for k, v := range av {
			if ov, ok := bv[k]; !ok || !equalAny(v, ov) {
				return false
			}
		}
		return true
	case []any:
		bv, ok := b.([]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if !equalAny(av[i], bv[i]) {
				return false
			}
		}
		return true
	case []string:
		bv, ok := b.([]string)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if av[i] != bv[i] {
				return false
			}
		}
		return true
	case []int:
		bv, ok := b.([]int)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if av[i] != bv[i] {
				return false
			}
		}
		return true
	case string:
		bv, ok := b.(string)
		return ok && av == bv
	case int:
		bv, ok := b.(int)
		return ok && av == bv
	case int64:
		bv, ok := b.(int64)
		return ok && av == bv
	case float64:
		bv, ok := b.(float64)
		return ok && av == bv
	case bool:
		bv, ok := b.(bool)
		return ok && av == bv
	default:
		return a == b
	}
}
{{- end}}
`

const equalsTestTemplate = `// Code generated by sudo-gen equals. DO NOT EDIT.

package {{.Package}}

import (
	"testing"
)
{{range .Structs}}
func Test{{.Name}}{{$.MethodName}}BothNil(t *testing.T) {
	var a, b *{{.Name}}
	if !a.{{$.MethodName}}(b) {
		t.Error("two nil pointers should be equal")
	}
}

func Test{{.Name}}{{$.MethodName}}OneNil(t *testing.T) {
	a := &{{.Name}}{}
	var b *{{.Name}}
	if a.{{$.MethodName}}(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.{{$.MethodName}}(a) {
		t.Error("nil should not equal non-nil")
	}
}

func Test{{.Name}}{{$.MethodName}}SamePointer(t *testing.T) {
	a := &{{.Name}}{}
	if !a.{{$.MethodName}}(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func Test{{.Name}}{{$.MethodName}}EmptyStructs(t *testing.T) {
	a := &{{.Name}}{}
	b := &{{.Name}}{}
	if !a.{{$.MethodName}}(b) {
		t.Error("two empty structs should be equal")
	}
}
{{end}}
`
