// Code generated by sudo-copy; DO NOT EDIT.

package copyobjects

import (
	"maps"
)

// Copy creates a deep copy of the Config.
func (c *Config) Copy() *Config {
	if c == nil {
		return nil
	}
	dst := &Config{}
	dst.Name = c.Name
	dst.Port = c.Port
	dst.MaxRetries = c.MaxRetries
	dst.Timeout = c.Timeout
	dst.Rate = c.Rate
	dst.Enabled = c.Enabled
	if c.EnabledPtr != nil {
		v := *c.EnabledPtr
		dst.EnabledPtr = &v
	}
	if c.Description != nil {
		v := *c.Description
		dst.Description = &v
	}
	if c.Hosts != nil {
		dst.Hosts = make([]string, len(c.Hosts))
		copy(dst.Hosts, c.Hosts)
	}
	if c.Ports != nil {
		dst.Ports = make([]int, len(c.Ports))
		copy(dst.Ports, c.Ports)
	}
	if c.Tags != nil {
		dst.Tags = make([]Tag, len(c.Tags))
		for i := range c.Tags {
			dst.Tags[i] = *c.Tags[i].Copy()
		}
	}
	if c.Labels != nil {
		dst.Labels = make(map[string]string, len(c.Labels))
		maps.Copy(dst.Labels, c.Labels)
	}
	if c.Metadata != nil {
		dst.Metadata = make(map[string]any, len(c.Metadata))
		for k, v := range c.Metadata {
			dst.Metadata[k] = deepCopyConfigAny(v)
		}
	}
	dst.Database = *c.Database.Copy()
	if c.DatabasePtr != nil {
		dst.DatabasePtr = c.DatabasePtr.Copy()
	}
	dst.CreatedAt = c.CreatedAt
	if c.UpdatedAt != nil {
		v := *c.UpdatedAt
		dst.UpdatedAt = &v
	}
	return dst
}

func deepCopyConfigAny(v any) any {
	if v == nil {
		return nil
	}
	switch val := v.(type) {
	case map[string]any:
		m := make(map[string]any, len(val))
		for k, v := range val {
			m[k] = deepCopyConfigAny(v)
		}
		return m
	case []any:
		s := make([]any, len(val))
		for i, v := range val {
			s[i] = deepCopyConfigAny(v)
		}
		return s
	case []string:
		s := make([]string, len(val))
		copy(s, val)
		return s
	case []int:
		s := make([]int, len(val))
		copy(s, val)
		return s
	default:
		return val
	}
}

func (c *Tag) Copy() *Tag {
	if c == nil {
		return nil
	}
	dst := &Tag{}
	dst.Key = c.Key
	dst.Value = c.Value
	return dst
}

func (c *DatabaseConfig) Copy() *DatabaseConfig {
	if c == nil {
		return nil
	}
	dst := &DatabaseConfig{}
	dst.Host = c.Host
	dst.Port = c.Port
	dst.Username = c.Username
	dst.Password = c.Password
	dst.SSLMode = c.SSLMode
	return dst
}
