// Code generated by sudo-gen merge. DO NOT EDIT.

package basic

func (c *Config) ApplyPartial(p *ConfigPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Name != nil {
		c.Name = *p.Name
	}
	if p.Port != nil {
		c.Port = *p.Port
	}
	if p.MaxRetries != nil {
		c.MaxRetries = *p.MaxRetries
	}
	if p.Timeout != nil {
		c.Timeout = *p.Timeout
	}
	if p.Rate != nil {
		c.Rate = *p.Rate
	}
	if p.Enabled != nil {
		c.Enabled = *p.Enabled
	}
	if p.Description != nil {
		v := *p.Description
		c.Description = &v
	}
	if p.Hosts != nil {
		c.Hosts = make([]string, len(p.Hosts))
		copy(c.Hosts, p.Hosts)
	}
	if p.Tags != nil {
		c.Tags = make([]Tag, len(p.Tags))
		copy(c.Tags, p.Tags)
	}
	if p.Labels != nil {
		if c.Labels == nil {
			c.Labels = make(map[string]string, len(p.Labels))
		}
		for k, v := range p.Labels {
			c.Labels[k] = v
		}
	}
	if p.Metadata != nil {
		if c.Metadata == nil {
			c.Metadata = make(map[string]any, len(p.Metadata))
		}
		for k, v := range p.Metadata {
			c.Metadata[k] = v
		}
	}
	if p.Database != nil {
		if c.Database == nil {
			c.Database = &DatabaseConfig{}
		}
		c.Database.ApplyPartial(p.Database)
	}
	if p.CreatedAt != nil {
		c.CreatedAt = *p.CreatedAt
	}
	if p.UpdatedAt != nil {
		v := *p.UpdatedAt
		c.UpdatedAt = &v
	}
}

func (c *Tag) ApplyPartial(p *TagPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Key != nil {
		c.Key = *p.Key
	}
	if p.Value != nil {
		c.Value = *p.Value
	}
}

func (c *DatabaseConfig) ApplyPartial(p *DatabaseConfigPartial) {
	if c == nil || p == nil {
		return
	}
	if p.Host != nil {
		c.Host = *p.Host
	}
	if p.Port != nil {
		c.Port = *p.Port
	}
	if p.Username != nil {
		c.Username = *p.Username
	}
	if p.Password != nil {
		c.Password = *p.Password
	}
	if p.SSLMode != nil {
		c.SSLMode = *p.SSLMode
	}
}
