// Code generated by sudo-gen merge. DO NOT EDIT.

package basic

import (
	"time"
)

type ConfigPartial struct {
	Name        *string                `json:"name,omitempty"`
	Port        *int                   `json:"port,omitempty"`
	MaxRetries  *int32                 `json:"max_retries,omitempty"`
	Timeout     *int64                 `json:"timeout,omitempty"`
	Rate        *float64               `json:"rate,omitempty"`
	Enabled     *bool                  `json:"enabled,omitempty"`
	Description *string                `json:"description,omitempty"`
	Hosts       []string               `json:"hosts,omitempty"`
	Tags        []Tag                  `json:"tags,omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Metadata    map[string]any         `json:"metadata,omitempty"`
	Database    *DatabaseConfigPartial `json:"database,omitempty"`
	CreatedAt   *time.Time             `json:"created_at,omitempty"`
	UpdatedAt   *time.Time             `json:"updated_at,omitempty"`
}

type TagPartial struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type DatabaseConfigPartial struct {
	Host     *string `json:"host,omitempty"`
	Port     *int    `json:"port,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
	SSLMode  *string `json:"ssl_mode,omitempty"`
}
