// Code generated by sudo-gen layerbroker. DO NOT EDIT.

package basic

import (
	"encoding/json"
	"testing"
	"time"
)

func configPtr[T any](v T) *T {
	return &v
}

func TestConfigLayerBrokerSubscriptionOrder(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Name: "initial", Port: 8080})
	layer1 := broker.Layer()
	var stringUpdates []string
	var intUpdates []int
	unsubString := broker.SubscribeName(func(v string) {
		stringUpdates = append(stringUpdates, v)
	})
	defer unsubString()
	if len(stringUpdates) != 1 || stringUpdates[0] != "initial" {
		t.Fatalf("expected initial Name callback, got %v", stringUpdates)
	}
	unsubInt := broker.SubscribePort(func(v int) {
		intUpdates = append(intUpdates, v)
	})
	defer unsubInt()
	if len(intUpdates) != 1 || intUpdates[0] != 8080 {
		t.Fatalf("expected initial Port callback, got %v", intUpdates)
	}
	layer1.Set(&ConfigPartial{Name: configPtr("updated")})
	if len(stringUpdates) != 2 || stringUpdates[1] != "updated" {
		t.Fatalf("expected Name update, got %v", stringUpdates)
	}
	if len(intUpdates) != 1 {
		t.Fatalf("Port subscriber should not have been called, got %v", intUpdates)
	}
	layer2 := broker.Layer()
	layer2.Set(&ConfigPartial{Port: configPtr(9090)})
	if len(intUpdates) != 2 || intUpdates[1] != 9090 {
		t.Fatalf("expected Port update, got %v", intUpdates)
	}
	if len(stringUpdates) != 2 {
		t.Fatalf("Name subscriber should not have been called, got %v", stringUpdates)
	}
	cfg := broker.Get()
	if cfg.Name != "updated" {
		t.Errorf("expected Name=updated, got %s", cfg.Name)
	}
	if cfg.Port != 9090 {
		t.Errorf("expected Port=9090, got %d", cfg.Port)
	}
}

func TestConfigLayerBrokerLowerLayerOverridden(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer1 := broker.Layer()
	layer2 := broker.Layer()
	layer1.Set(&ConfigPartial{Name: configPtr("one")})
	layer2.Set(&ConfigPartial{Name: configPtr("two"), Port: configPtr(8080)})
	var updates []string
	unsub := broker.SubscribeName(func(v string) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] != "two" {
		t.Fatalf("expected initial callback with 'two', got %v", updates)
	}
	layer1.Set(&ConfigPartial{Name: configPtr("three")})
	if len(updates) != 1 {
		t.Fatalf("expected no update when lower layer is overridden, got %v", updates)
	}
	cfg := broker.Get()
	if cfg.Name != "two" {
		t.Errorf("expected Name=two, got %s", cfg.Name)
	}
}

func TestConfigLayerBrokerMultipleLayersPriority(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer1 := broker.Layer()
	layer2 := broker.Layer()
	layer3 := broker.Layer()

	// Set same field in all layers - last layer should win
	layer1.Set(&ConfigPartial{Name: configPtr("layer1")})
	layer2.Set(&ConfigPartial{Name: configPtr("layer2")})
	layer3.Set(&ConfigPartial{Name: configPtr("layer3")})

	cfg := broker.Get()
	if cfg.Name != "layer3" {
		t.Errorf("expected Name=layer3 (last layer should win), got %s", cfg.Name)
	}

	// Update layer2, but layer3 still wins
	layer2.Set(&ConfigPartial{Name: configPtr("layer2-updated")})
	cfg = broker.Get()
	if cfg.Name != "layer3" {
		t.Errorf("expected Name=layer3 (higher layer should still win), got %s", cfg.Name)
	}
}

func TestConfigLayerBrokerMultipleSubscribers(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Name: "initial"})
	var updates1, updates2 []string

	unsub1 := broker.SubscribeName(func(v string) {
		updates1 = append(updates1, v)
	})
	defer unsub1()

	unsub2 := broker.SubscribeName(func(v string) {
		updates2 = append(updates2, v)
	})
	defer unsub2()

	if len(updates1) != 1 || len(updates2) != 1 {
		t.Fatalf("expected both subscribers to get initial value")
	}

	broker.Layer().Set(&ConfigPartial{Name: configPtr("updated")})

	if len(updates1) != 2 || updates1[1] != "updated" {
		t.Errorf("expected subscriber1 to get update, got %v", updates1)
	}
	if len(updates2) != 2 || updates2[1] != "updated" {
		t.Errorf("expected subscriber2 to get update, got %v", updates2)
	}
}

func TestConfigLayerBrokerUnsubscribe(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Name: "test"})
	var updates []string
	unsub := broker.SubscribeName(func(v string) {
		updates = append(updates, v)
	})
	if len(updates) != 1 {
		t.Fatalf("expected 1 update, got %d", len(updates))
	}
	broker.Layer().Set(&ConfigPartial{Name: configPtr("changed")})
	if len(updates) != 2 {
		t.Fatalf("expected 2 updates, got %d", len(updates))
	}
	unsub()
	broker.Layer().Set(&ConfigPartial{Name: configPtr("ignored")})
	if len(updates) != 2 {
		t.Fatalf("expected 2 updates after unsubscribe, got %d", len(updates))
	}
	if broker.Get().Name != "ignored" {
		t.Errorf("expected Name=ignored, got %s", broker.Get().Name)
	}
}

func TestConfigLayerBrokerSubscribeToEmptyField(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	var callCount int
	unsub := broker.SubscribeName(func(v string) {
		callCount++
	})
	defer unsub()

	// Should not be called initially since field is empty
	if callCount != 0 {
		t.Errorf("expected 0 calls for empty field, got %d", callCount)
	}

	// Should be called when field is set
	broker.Layer().Set(&ConfigPartial{Name: configPtr("test")})
	if callCount != 1 {
		t.Errorf("expected 1 call after setting field, got %d", callCount)
	}
}

func TestConfigLayerBrokerNoChangeNoNotify(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Port: 42})
	var updates []int
	unsub := broker.SubscribePort(func(v int) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 {
		t.Fatalf("expected 1 update, got %d", len(updates))
	}
	// Setting to same value should NOT trigger callback
	broker.Layer().Set(&ConfigPartial{Port: configPtr(42)})
	if len(updates) != 1 {
		t.Fatalf("expected 1 update (no change), got %d", len(updates))
	}
	// Setting to different value should trigger callback
	broker.Layer().Set(&ConfigPartial{Port: configPtr(100)})
	if len(updates) != 2 || updates[1] != 100 {
		t.Fatalf("expected 2 updates with 100, got %v", updates)
	}
}

func TestConfigLayerBrokerZeroValueUpdate(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Port: 42})
	var updates []int
	unsub := broker.SubscribePort(func(v int) {
		updates = append(updates, v)
	})
	defer unsub()

	// Setting to zero value should trigger callback
	broker.Layer().Set(&ConfigPartial{Port: configPtr(0)})
	if len(updates) != 2 || updates[1] != 0 {
		t.Errorf("expected zero value update, got %v", updates)
	}
}

func TestConfigLayerBrokerNilPartial(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{})
	broker.Layer().Set(nil) // should not panic
}

func TestConfigLayerBrokerGetReturnsIndependentCopy(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{})
	cfg1 := broker.Get()
	cfg2 := broker.Get()

	if cfg1 == cfg2 {
		t.Error("Get() should return independent copies, not the same pointer")
	}
}

func TestConfigLayerBrokerConcurrentLayerCreation(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	done := make(chan bool)

	// Create layers concurrently
	for i := 0; i < 10; i++ {
		go func() {
			layer := broker.Layer()
			if layer == nil {
				t.Error("Layer() returned nil")
			}
			done <- true
		}()
	}

	for i := 0; i < 10; i++ {
		<-done
	}
}

func TestConfigLayerBrokerBaseConfigPreserved(t *testing.T) {

	broker := NewConfigLayerBroker(&Config{Name: "base"})
	layer := broker.Layer()
	layer.Set(&ConfigPartial{Name: configPtr("layer")})

	cfg := broker.Get()
	if cfg.Name != "layer" {
		t.Errorf("expected Name=layer, got %s", cfg.Name)
	}

	// Create new broker to verify base is not mutated
	broker2 := NewConfigLayerBroker(&Config{Name: "base"})
	cfg2 := broker2.Get()
	if cfg2.Name != "base" {
		t.Errorf("base config should be preserved, got %s", cfg2.Name)
	}

}

func TestConfigLayerBrokerSubscribeMaxRetries(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{MaxRetries: 42})
	var updates []int32
	unsub := broker.SubscribeMaxRetries(func(v int32) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] != 42 {
		t.Fatalf("expected initial callback with 42, got %v", updates)
	}
	broker.Layer().Set(&ConfigPartial{MaxRetries: configPtr(int32(100))})
	if len(updates) != 2 || updates[1] != 100 {
		t.Fatalf("expected update callback with 100, got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeTimeout(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Timeout: 42})
	var updates []int64
	unsub := broker.SubscribeTimeout(func(v int64) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] != 42 {
		t.Fatalf("expected initial callback with 42, got %v", updates)
	}
	broker.Layer().Set(&ConfigPartial{Timeout: configPtr(int64(100))})
	if len(updates) != 2 || updates[1] != 100 {
		t.Fatalf("expected update callback with 100, got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeRate(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Rate: 3.14})
	var updates []float64
	unsub := broker.SubscribeRate(func(v float64) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] != 3.14 {
		t.Fatalf("expected initial callback with 3.14, got %v", updates)
	}
	broker.Layer().Set(&ConfigPartial{Rate: configPtr(2.71)})
	if len(updates) != 2 || updates[1] != 2.71 {
		t.Fatalf("expected update callback with 2.71, got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeEnabled(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Enabled: true})
	var updates []bool
	unsub := broker.SubscribeEnabled(func(v bool) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || !updates[0] {
		t.Fatalf("expected initial callback with true, got %v", updates)
	}
	broker.Layer().Set(&ConfigPartial{Enabled: configPtr(false)})
	if len(updates) != 2 || updates[1] {
		t.Fatalf("expected update callback with false, got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeDescriptionPointer(t *testing.T) {
	val := "initial"
	broker := NewConfigLayerBroker(&Config{Description: &val})
	var updates []*string
	unsub := broker.SubscribeDescription(func(v *string) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] == nil || *updates[0] != "initial" {
		t.Fatalf("expected initial callback with 'initial', got %v", updates)
	}
	broker.Layer().Set(&ConfigPartial{Description: configPtr("updated")})
	if len(updates) != 2 || updates[1] == nil || *updates[1] != "updated" {
		t.Fatalf("expected update callback with 'updated', got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeHostsSlice(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Hosts: []string{}})
	var callCount int
	unsub := broker.SubscribeHosts(func(v []string) {
		callCount++
	})
	defer unsub()
	// Empty slice is non-nil, so should get initial callback
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
	// Set a new slice
	broker.Layer().Set(&ConfigPartial{Hosts: make([]string, 3)})
	if callCount != 2 {
		t.Fatalf("expected 2 callbacks after update, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeTagsSlice(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Tags: []Tag{}})
	var callCount int
	unsub := broker.SubscribeTags(func(v []Tag) {
		callCount++
	})
	defer unsub()
	// Empty slice is non-nil, so should get initial callback
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
	// Set a new slice
	broker.Layer().Set(&ConfigPartial{Tags: make([]Tag, 3)})
	if callCount != 2 {
		t.Fatalf("expected 2 callbacks after update, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeLabelsMap(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Labels: make(map[string]string)})
	var callCount int
	unsub := broker.SubscribeLabels(func(v map[string]string) {
		callCount++
	})
	defer unsub()
	// Empty map is non-nil, so should get initial callback
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeMetadataMap(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Metadata: make(map[string]any)})
	var callCount int
	unsub := broker.SubscribeMetadata(func(v map[string]any) {
		callCount++
	})
	defer unsub()
	// Empty map is non-nil, so should get initial callback
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeDatabaseStruct(t *testing.T) {
	broker := NewConfigLayerBroker(&Config{Database: &DatabaseConfig{}})
	var callCount int
	unsub := broker.SubscribeDatabase(func(v *DatabaseConfig) {
		callCount++
	})
	defer unsub()
	if callCount != 1 {
		t.Fatalf("expected 1 initial callback, got %d", callCount)
	}
}

func TestConfigLayerBrokerSubscribeCreatedAtTime(t *testing.T) {
	now := time.Now()
	broker := NewConfigLayerBroker(&Config{CreatedAt: now})
	var updates []time.Time
	unsub := broker.SubscribeCreatedAt(func(v time.Time) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || !updates[0].Equal(now) {
		t.Fatalf("expected initial callback with current time, got %v", updates)
	}
	later := now.Add(time.Hour)
	broker.Layer().Set(&ConfigPartial{CreatedAt: &later})
	if len(updates) != 2 || !updates[1].Equal(later) {
		t.Fatalf("expected update callback with later time, got %v", updates)
	}
}

func TestConfigLayerBrokerSubscribeUpdatedAtTimePointer(t *testing.T) {
	now := time.Now()
	broker := NewConfigLayerBroker(&Config{UpdatedAt: &now})
	var updates []*time.Time
	unsub := broker.SubscribeUpdatedAt(func(v *time.Time) {
		updates = append(updates, v)
	})
	defer unsub()
	if len(updates) != 1 || updates[0] == nil || !updates[0].Equal(now) {
		t.Fatalf("expected initial callback with current time, got %v", updates)
	}
}

func TestConfigLayerBrokerMarshalJSON(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	layer.Set(&ConfigPartial{Name: configPtr("test")})
	data, err := json.Marshal(broker)
	if err != nil {
		t.Fatalf("MarshalJSON failed: %v", err)
	}
	if len(data) == 0 {
		t.Error("expected non-empty JSON output")
	}
	// Verify it's valid JSON
	var result map[string]any
	if err := json.Unmarshal(data, &result); err != nil {
		t.Fatalf("result is not valid JSON: %v", err)
	}
	if _, ok := result["base"]; !ok {
		t.Error("expected 'base' field in JSON output")
	}
	if _, ok := result["layers"]; !ok {
		t.Error("expected 'layers' field in JSON output")
	}
	if _, ok := result["final"]; !ok {
		t.Error("expected 'final' field in JSON output")
	}
}

func TestConfigLayerBrokerMarshalJSONEmpty(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	data, err := json.Marshal(broker)
	if err != nil {
		t.Fatalf("MarshalJSON failed: %v", err)
	}
	if len(data) == 0 {
		t.Error("expected non-empty JSON output")
	}
}

func TestConfigLayerBrokerSetAllFieldTypes(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	// Test setting all field types to exercise mergePartial
	partial := &ConfigPartial{}
	partial.Name = configPtr("test")
	partial.Port = configPtr(42)
	partial.MaxRetries = configPtr(int32(42))
	partial.Timeout = configPtr(int64(42))
	partial.Rate = configPtr(3.14)
	partial.Enabled = configPtr(true)

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetSliceAndMapFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{}
	partial.Hosts = make([]string, 1)
	partial.Tags = make([]Tag, 1)
	partial.Labels = make(map[string]string)
	partial.Metadata = make(map[string]any)

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetPointerFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{}
	partial.Description = configPtr("test")

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting fields")
	}
}

func TestConfigLayerBrokerSetNestedStructDatabase(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	partial := &ConfigPartial{
		Database: &DatabaseConfigPartial{},
	}
	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting nested struct")
	}
}

func TestConfigLayerBrokerSetTimeFields(t *testing.T) {
	broker := NewConfigLayerBroker(nil)
	layer := broker.Layer()
	now := time.Now()
	partial := &ConfigPartial{}
	partial.CreatedAt = &now

	partial.UpdatedAt = &now

	layer.Set(partial)
	cfg := broker.Get()
	if cfg == nil {
		t.Fatal("Get() returned nil after setting time fields")
	}
}
