// Code generated by sudo-gen manager. DO NOT EDIT.

package basic

import (
	"reflect"
	"sync"
	"time"
)

// ConfigManager provides thread-safe access to Config with change subscriptions.
type ConfigManager struct {
	mu          sync.RWMutex
	config      *Config
	subscribers map[string][]any
}

// NewConfigManager creates a new manager wrapping the given config.
// If cfg is nil, an empty config is used.
func NewConfigManager(cfg *Config) *ConfigManager {
	if cfg == nil {
		cfg = &Config{}
	}
	return &ConfigManager{
		config:      cfg.Copy(),
		subscribers: make(map[string][]any),
	}
}

// Get returns a deep copy of the current configuration.
func (m *ConfigManager) Get() *Config {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.config.Copy()
}

// Transaction returns a new transaction for making changes.
func (m *ConfigManager) Transaction() *ConfigTransaction {
	return &ConfigTransaction{
		manager: m,
		partial: &ConfigPartial{},
	}
}

// Path constants for subscriptions.
const (
	ConfigPathName             = "Name"
	ConfigPathPort             = "Port"
	ConfigPathMaxRetries       = "MaxRetries"
	ConfigPathTimeout          = "Timeout"
	ConfigPathRate             = "Rate"
	ConfigPathEnabled          = "Enabled"
	ConfigPathDescription      = "Description"
	ConfigPathHosts            = "Hosts"
	ConfigPathTags             = "Tags"
	ConfigPathLabels           = "Labels"
	ConfigPathMetadata         = "Metadata"
	ConfigPathDatabase         = "Database"
	ConfigPathDatabaseHost     = "Database.Host"
	ConfigPathDatabasePort     = "Database.Port"
	ConfigPathDatabaseUsername = "Database.Username"
	ConfigPathDatabasePassword = "Database.Password"
	ConfigPathDatabaseSSLMode  = "Database.SSLMode"
	ConfigPathCreatedAt        = "CreatedAt"
	ConfigPathUpdatedAt        = "UpdatedAt"
)

// SubscribeName subscribes to changes on Name.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeName(callback func(string)) func() {
	return m.subscribe(ConfigPathName, callback)
}

// SubscribePort subscribes to changes on Port.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribePort(callback func(int)) func() {
	return m.subscribe(ConfigPathPort, callback)
}

// SubscribeMaxRetries subscribes to changes on MaxRetries.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeMaxRetries(callback func(int32)) func() {
	return m.subscribe(ConfigPathMaxRetries, callback)
}

// SubscribeTimeout subscribes to changes on Timeout.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeTimeout(callback func(int64)) func() {
	return m.subscribe(ConfigPathTimeout, callback)
}

// SubscribeRate subscribes to changes on Rate.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeRate(callback func(float64)) func() {
	return m.subscribe(ConfigPathRate, callback)
}

// SubscribeEnabled subscribes to changes on Enabled.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeEnabled(callback func(bool)) func() {
	return m.subscribe(ConfigPathEnabled, callback)
}

// SubscribeDescription subscribes to changes on Description.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDescription(callback func(*string)) func() {
	return m.subscribe(ConfigPathDescription, callback)
}

// SubscribeHosts subscribes to changes on Hosts.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeHosts(callback func([]string)) func() {
	return m.subscribe(ConfigPathHosts, callback)
}

// SubscribeTags subscribes to changes on Tags.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeTags(callback func([]Tag)) func() {
	return m.subscribe(ConfigPathTags, callback)
}

// SubscribeLabels subscribes to changes on Labels.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeLabels(callback func(map[string]string)) func() {
	return m.subscribe(ConfigPathLabels, callback)
}

// SubscribeMetadata subscribes to changes on Metadata.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeMetadata(callback func(map[string]any)) func() {
	return m.subscribe(ConfigPathMetadata, callback)
}

// SubscribeDatabase subscribes to changes on Database.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabase(callback func(*DatabaseConfig)) func() {
	return m.subscribe(ConfigPathDatabase, callback)
}

// SubscribeDatabaseHost subscribes to changes on Database.Host.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabaseHost(callback func(string)) func() {
	return m.subscribe(ConfigPathDatabaseHost, callback)
}

// SubscribeDatabasePort subscribes to changes on Database.Port.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabasePort(callback func(int)) func() {
	return m.subscribe(ConfigPathDatabasePort, callback)
}

// SubscribeDatabaseUsername subscribes to changes on Database.Username.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabaseUsername(callback func(string)) func() {
	return m.subscribe(ConfigPathDatabaseUsername, callback)
}

// SubscribeDatabasePassword subscribes to changes on Database.Password.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabasePassword(callback func(string)) func() {
	return m.subscribe(ConfigPathDatabasePassword, callback)
}

// SubscribeDatabaseSSLMode subscribes to changes on Database.SSLMode.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeDatabaseSSLMode(callback func(string)) func() {
	return m.subscribe(ConfigPathDatabaseSSLMode, callback)
}

// SubscribeCreatedAt subscribes to changes on CreatedAt.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeCreatedAt(callback func(time.Time)) func() {
	return m.subscribe(ConfigPathCreatedAt, callback)
}

// SubscribeUpdatedAt subscribes to changes on UpdatedAt.
// The callback is invoked immediately if the value is set, and on future changes.
// Returns an unsubscribe function.
func (m *ConfigManager) SubscribeUpdatedAt(callback func(*time.Time)) func() {
	return m.subscribe(ConfigPathUpdatedAt, callback)
}

// Subscribe registers a callback for the given path.
// The callback type must match the field type at the path.
// Returns an unsubscribe function.
func (m *ConfigManager) Subscribe(path string, callback any) func() {
	return m.subscribe(path, callback)
}

func (m *ConfigManager) subscribe(path string, callback any) func() {
	m.mu.Lock()
	m.subscribers[path] = append(m.subscribers[path], callback)
	currentValue := m.getValueAtPath(path)
	m.mu.Unlock()
	if !isZeroValue(currentValue) {
		invokeCallback(callback, currentValue)
	}
	return func() {
		m.mu.Lock()
		defer m.mu.Unlock()
		subs := m.subscribers[path]
		for i, sub := range subs {
			if reflect.ValueOf(sub).Pointer() == reflect.ValueOf(callback).Pointer() {
				m.subscribers[path] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
	}
}

func (m *ConfigManager) getValueAtPath(path string) any {
	switch path {
	case ConfigPathName:
		return m.config.Name
	case ConfigPathPort:
		return m.config.Port
	case ConfigPathMaxRetries:
		return m.config.MaxRetries
	case ConfigPathTimeout:
		return m.config.Timeout
	case ConfigPathRate:
		return m.config.Rate
	case ConfigPathEnabled:
		return m.config.Enabled
	case ConfigPathDescription:
		return m.config.Description
	case ConfigPathHosts:
		return m.config.Hosts
	case ConfigPathTags:
		return m.config.Tags
	case ConfigPathLabels:
		return m.config.Labels
	case ConfigPathMetadata:
		return m.config.Metadata
	case ConfigPathDatabase:
		return m.config.Database
	case ConfigPathDatabaseHost:
		if m.config.Database == nil {
			return ""
		}
		return m.config.Database.Host
	case ConfigPathDatabasePort:
		if m.config.Database == nil {
			return 0
		}
		return m.config.Database.Port
	case ConfigPathDatabaseUsername:
		if m.config.Database == nil {
			return ""
		}
		return m.config.Database.Username
	case ConfigPathDatabasePassword:
		if m.config.Database == nil {
			return ""
		}
		return m.config.Database.Password
	case ConfigPathDatabaseSSLMode:
		if m.config.Database == nil {
			return ""
		}
		return m.config.Database.SSLMode
	case ConfigPathCreatedAt:
		return m.config.CreatedAt
	case ConfigPathUpdatedAt:
		return m.config.UpdatedAt
	}
	return nil
}

func (m *ConfigManager) notifySubscribers(path string, value any) {
	for _, callback := range m.subscribers[path] {
		invokeCallback(callback, value)
	}
}

func invokeCallback(callback any, value any) {
	reflect.ValueOf(callback).Call([]reflect.Value{reflect.ValueOf(value)})
}

func isZeroValue(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Ptr, reflect.Slice, reflect.Map, reflect.Interface:
		return rv.IsNil()
	}
	return reflect.DeepEqual(v, reflect.Zero(reflect.TypeOf(v)).Interface())
}

// ConfigTransaction holds pending changes to be applied.
type ConfigTransaction struct {
	manager *ConfigManager
	partial *ConfigPartial
}

// SetName sets Name in this transaction.
func (t *ConfigTransaction) SetName(v string) *ConfigTransaction {
	t.partial.Name = &v
	return t
}

// SetPort sets Port in this transaction.
func (t *ConfigTransaction) SetPort(v int) *ConfigTransaction {
	t.partial.Port = &v
	return t
}

// SetMaxRetries sets MaxRetries in this transaction.
func (t *ConfigTransaction) SetMaxRetries(v int32) *ConfigTransaction {
	t.partial.MaxRetries = &v
	return t
}

// SetTimeout sets Timeout in this transaction.
func (t *ConfigTransaction) SetTimeout(v int64) *ConfigTransaction {
	t.partial.Timeout = &v
	return t
}

// SetRate sets Rate in this transaction.
func (t *ConfigTransaction) SetRate(v float64) *ConfigTransaction {
	t.partial.Rate = &v
	return t
}

// SetEnabled sets Enabled in this transaction.
func (t *ConfigTransaction) SetEnabled(v bool) *ConfigTransaction {
	t.partial.Enabled = &v
	return t
}

// SetDescription sets Description in this transaction.
func (t *ConfigTransaction) SetDescription(v *string) *ConfigTransaction {
	t.partial.Description = v
	return t
}

// SetHosts sets Hosts in this transaction.
func (t *ConfigTransaction) SetHosts(v []string) *ConfigTransaction {
	t.partial.Hosts = v
	return t
}

// SetTags sets Tags in this transaction.
func (t *ConfigTransaction) SetTags(v []Tag) *ConfigTransaction {
	t.partial.Tags = v
	return t
}

// SetLabels sets Labels in this transaction.
func (t *ConfigTransaction) SetLabels(v map[string]string) *ConfigTransaction {
	t.partial.Labels = v
	return t
}

// SetMetadata sets Metadata in this transaction.
func (t *ConfigTransaction) SetMetadata(v map[string]any) *ConfigTransaction {
	t.partial.Metadata = v
	return t
}

// SetDatabaseHost sets Database.Host in this transaction.
func (t *ConfigTransaction) SetDatabaseHost(v string) *ConfigTransaction {
	if t.partial.Database == nil {
		t.partial.Database = &DatabaseConfigPartial{}
	}
	t.partial.Database.Host = &v
	return t
}

// SetDatabasePort sets Database.Port in this transaction.
func (t *ConfigTransaction) SetDatabasePort(v int) *ConfigTransaction {
	if t.partial.Database == nil {
		t.partial.Database = &DatabaseConfigPartial{}
	}
	t.partial.Database.Port = &v
	return t
}

// SetDatabaseUsername sets Database.Username in this transaction.
func (t *ConfigTransaction) SetDatabaseUsername(v string) *ConfigTransaction {
	if t.partial.Database == nil {
		t.partial.Database = &DatabaseConfigPartial{}
	}
	t.partial.Database.Username = &v
	return t
}

// SetDatabasePassword sets Database.Password in this transaction.
func (t *ConfigTransaction) SetDatabasePassword(v string) *ConfigTransaction {
	if t.partial.Database == nil {
		t.partial.Database = &DatabaseConfigPartial{}
	}
	t.partial.Database.Password = &v
	return t
}

// SetDatabaseSSLMode sets Database.SSLMode in this transaction.
func (t *ConfigTransaction) SetDatabaseSSLMode(v string) *ConfigTransaction {
	if t.partial.Database == nil {
		t.partial.Database = &DatabaseConfigPartial{}
	}
	t.partial.Database.SSLMode = &v
	return t
}

// SetCreatedAt sets CreatedAt in this transaction.
func (t *ConfigTransaction) SetCreatedAt(v time.Time) *ConfigTransaction {
	t.partial.CreatedAt = &v
	return t
}

// SetUpdatedAt sets UpdatedAt in this transaction.
func (t *ConfigTransaction) SetUpdatedAt(v *time.Time) *ConfigTransaction {
	t.partial.UpdatedAt = v
	return t
}

// Commit applies all changes and notifies subscribers.
// Returns the paths that were changed.
func (t *ConfigTransaction) Commit() []string {
	t.manager.mu.Lock()
	defer t.manager.mu.Unlock()
	oldValues := make(map[string]any, len(t.manager.subscribers))
	for path := range t.manager.subscribers {
		oldValues[path] = t.manager.getValueAtPath(path)
	}
	t.manager.config.ApplyPartial(t.partial)
	var changed []string
	for path, oldVal := range oldValues {
		newVal := t.manager.getValueAtPath(path)
		if !reflect.DeepEqual(oldVal, newVal) {
			changed = append(changed, path)
			t.manager.notifySubscribers(path, newVal)
		}
	}
	return changed
}
