// Code generated by sudo-gen equals. DO NOT EDIT.

package basic

import (
	"testing"
)

func TestConfigEqualBothNil(t *testing.T) {
	var a, b *Config
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestConfigEqualOneNil(t *testing.T) {
	a := &Config{}
	var b *Config
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestConfigEqualSamePointer(t *testing.T) {
	a := &Config{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestConfigEqualEmptyStructs(t *testing.T) {
	a := &Config{}
	b := &Config{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}

func TestTagEqualBothNil(t *testing.T) {
	var a, b *Tag
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestTagEqualOneNil(t *testing.T) {
	a := &Tag{}
	var b *Tag
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestTagEqualSamePointer(t *testing.T) {
	a := &Tag{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestTagEqualEmptyStructs(t *testing.T) {
	a := &Tag{}
	b := &Tag{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}

func TestDatabaseConfigEqualBothNil(t *testing.T) {
	var a, b *DatabaseConfig
	if !a.Equal(b) {
		t.Error("two nil pointers should be equal")
	}
}

func TestDatabaseConfigEqualOneNil(t *testing.T) {
	a := &DatabaseConfig{}
	var b *DatabaseConfig
	if a.Equal(b) {
		t.Error("non-nil should not equal nil")
	}
	if b.Equal(a) {
		t.Error("nil should not equal non-nil")
	}
}

func TestDatabaseConfigEqualSamePointer(t *testing.T) {
	a := &DatabaseConfig{}
	if !a.Equal(a) {
		t.Error("same pointer should be equal to itself")
	}
}

func TestDatabaseConfigEqualEmptyStructs(t *testing.T) {
	a := &DatabaseConfig{}
	b := &DatabaseConfig{}
	if !a.Equal(b) {
		t.Error("two empty structs should be equal")
	}
}
