// Code generated by sudo-gen equals. DO NOT EDIT.

package basic

// Equal returns true if c and other have the same values.
func (c *Config) Equal(other *Config) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Name != other.Name {
		return false
	}
	if c.Port != other.Port {
		return false
	}
	if c.MaxRetries != other.MaxRetries {
		return false
	}
	if c.Timeout != other.Timeout {
		return false
	}
	if c.Rate != other.Rate {
		return false
	}
	if c.Enabled != other.Enabled {
		return false
	}
	if (c.Description == nil) != (other.Description == nil) {
		return false
	}
	if c.Description != nil && *c.Description != *other.Description {
		return false
	}
	if len(c.Hosts) != len(other.Hosts) {
		return false
	}
	for i := range c.Hosts {
		if c.Hosts[i] != other.Hosts[i] {
			return false
		}
	}
	if len(c.Tags) != len(other.Tags) {
		return false
	}
	for i := range c.Tags {
		if !c.Tags[i].Equal(&other.Tags[i]) {
			return false
		}
	}
	if len(c.Labels) != len(other.Labels) {
		return false
	}
	for k, v := range c.Labels {
		ov, ok := other.Labels[k]
		if !ok {
			return false
		}
		if v != ov {
			return false
		}
	}
	if len(c.Metadata) != len(other.Metadata) {
		return false
	}
	for k, v := range c.Metadata {
		ov, ok := other.Metadata[k]
		if !ok {
			return false
		}
		if !equalAny(v, ov) {
			return false
		}
	}
	if !c.Database.Equal(other.Database) {
		return false
	}
	if !c.CreatedAt.Equal(other.CreatedAt) {
		return false
	}
	if (c.UpdatedAt == nil) != (other.UpdatedAt == nil) {
		return false
	}
	if c.UpdatedAt != nil && !c.UpdatedAt.Equal(*other.UpdatedAt) {
		return false
	}
	return true
}

// Equal returns true if c and other have the same values.
func (c *Tag) Equal(other *Tag) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Key != other.Key {
		return false
	}
	if c.Value != other.Value {
		return false
	}
	return true
}

// Equal returns true if c and other have the same values.
func (c *DatabaseConfig) Equal(other *DatabaseConfig) bool {
	if c == other {
		return true
	}
	if c == nil || other == nil {
		return false
	}
	if c.Host != other.Host {
		return false
	}
	if c.Port != other.Port {
		return false
	}
	if c.Username != other.Username {
		return false
	}
	if c.Password != other.Password {
		return false
	}
	if c.SSLMode != other.SSLMode {
		return false
	}
	return true
}

func equalAny(a, b any) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	switch av := a.(type) {
	case map[string]any:
		bv, ok := b.(map[string]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for k, v := range av {
			if ov, ok := bv[k]; !ok || !equalAny(v, ov) {
				return false
			}
		}
		return true
	case []any:
		bv, ok := b.([]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if !equalAny(av[i], bv[i]) {
				return false
			}
		}
		return true
	case []string:
		bv, ok := b.([]string)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if av[i] != bv[i] {
				return false
			}
		}
		return true
	case []int:
		bv, ok := b.([]int)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if av[i] != bv[i] {
				return false
			}
		}
		return true
	case string:
		bv, ok := b.(string)
		return ok && av == bv
	case int:
		bv, ok := b.(int)
		return ok && av == bv
	case int64:
		bv, ok := b.(int64)
		return ok && av == bv
	case float64:
		bv, ok := b.(float64)
		return ok && av == bv
	case bool:
		bv, ok := b.(bool)
		return ok && av == bv
	default:
		return a == b
	}
}
